export type ErrorSeverity = 'error' | 'warning' | 'info';

export const ERROR_CODES = {
  UNKNOWN: {
    UNEXPECTED: 'UNKNOWN_UNEXPECTED',
    RUNTIME: 'UNKNOWN_RUNTIME',
    UNHANDLED_REJECTION: 'UNKNOWN_UNHANDLED_REJECTION',
  },
  VALIDATION: {
    REQUIRED: 'VALIDATION_REQUIRED',
    INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
    OUT_OF_RANGE: 'VALIDATION_OUT_OF_RANGE',
  },
  STATE: {
    INVALID_STATE: 'STATE_INVALID_STATE',
    NOT_READY: 'STATE_NOT_READY',
    LOAD_FAILED: 'STATE_LOAD_FAILED',
  },
  NETWORK: {
    REQUEST_FAILED: 'NETWORK_REQUEST_FAILED',
    TIMEOUT: 'NETWORK_TIMEOUT',
    UNAUTHORIZED: 'NETWORK_UNAUTHORIZED',
  },
  DB: {
    READ_FAILED: 'DB_READ_FAILED',
    WRITE_FAILED: 'DB_WRITE_FAILED',
  },
  SYNC: {
    LOAD_FAILED: 'SYNC_LOAD_FAILED',
    SAVE_FAILED: 'SYNC_SAVE_FAILED',
    CONFLICT: 'SYNC_CONFLICT',
  },
  UI: {
    ACTION_FAILED: 'UI_ACTION_FAILED',
    COPY_FAILED: 'UI_COPY_FAILED',
  },
  APP: {
    BOOTSTRAP_FAILED: 'APP_BOOTSTRAP_FAILED',
  },
  ROSTER_SWITCHER: {
    REFRESH_FAILED: 'ROSTER_SWITCHER_REFRESH_FAILED',
    ACTION_FAILED: 'ROSTER_SWITCHER_ACTION_FAILED',
    TOGGLE_VISIBLE_FAILED: 'ROSTER_SWITCHER_TOGGLE_VISIBLE_FAILED',
  },
  WEEKLY: {
    LOAD_ALL_FAILED: 'WEEKLY_LOAD_ALL_FAILED',
    LOAD_VISIBLE_ROSTERS_FAILED: 'WEEKLY_LOAD_VISIBLE_ROSTERS_FAILED',
    API_READY_TIMEOUT: 'WEEKLY_API_READY_TIMEOUT',
    API_READY_FAILED: 'WEEKLY_API_READY_FAILED',
    SETTINGS_REFRESH_FAILED: 'WEEKLY_SETTINGS_REFRESH_FAILED',
    EMPTY_CARDS: 'WEEKLY_EMPTY_CARDS',
    LOAD_FROM_DB_FAILED: 'WEEKLY_LOAD_FROM_DB_FAILED',
    DEBUG_COPY_FAILED: 'WEEKLY_DEBUG_COPY_FAILED',
  },
  FRIENDS: {
    INIT_FAILED: 'FRIENDS_INIT_FAILED',
    ACTIVE_ROSTER_REFRESH_FAILED: 'FRIENDS_ACTIVE_ROSTER_REFRESH_FAILED',
    REFRESH_FAILED: 'FRIENDS_REFRESH_FAILED',
    UPLOAD_FAILED: 'FRIENDS_UPLOAD_FAILED',
    AUTO_UPLOAD_FAILED: 'FRIENDS_AUTO_UPLOAD_FAILED',
    PIN_SYNC_FAILED: 'FRIENDS_PIN_SYNC_FAILED',
    ADD_FRIEND_FAILED: 'FRIENDS_ADD_FRIEND_FAILED',
    COPY_CODE_FAILED: 'FRIENDS_COPY_CODE_FAILED',
    SAVE_CONFIG_FAILED: 'FRIENDS_SAVE_CONFIG_FAILED',
  },
} as const;

export type ErrorCodeGroup = typeof ERROR_CODES;
type NestedRecordValue<T> = T extends Record<string, infer V> ? V : never;
export type KnownErrorCode = NestedRecordValue<NestedRecordValue<ErrorCodeGroup>>;

const knownCodeSet = new Set<string>(
  Object.values(ERROR_CODES)
    .flatMap((group) => Object.values(group))
);

export function isKnownErrorCode(code: string): code is KnownErrorCode {
  return knownCodeSet.has(code);
}
